version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          - RAILS_ENV: 'test'
      - image: circleci/mysql:8.0.23
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'
        command: --default-authentication-plugin=mysql_native_password

    working_directory: ~/Remoshare

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: bundler install
          command: gem install bundler -v 2.1.4

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-

      - run:
          name: Yarn のインストール
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: webpack installを実行
          command: bundle exec bin/webpack

      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load

      - run:
          name: Rubocopの実行
          command: bundle exec rubocop

      - run:
          name: RSpecの実行
          command: bundle exec rspec -b --format documentation

      - store_test_results:
          path: /tmp/test-results

      - add_ssh_keys:
          fingerprints: "74:c5:97:41:84:41:fa:f6:20:34:f4:75:86:22:a3:e1"

      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy
